export const ActionTypes = {
    FETCH_PRODUCTS : 'FETCH_PRODUCTS',
    FETCH_SINGLE_PRODUCT : 'FETCH_SINGLE_PRODUCT',
    FETCH_USER :' FETCH_USER',
    FETCH_NAVDATA : 'FETCH_NAVDATA',
    ADD_PRODUCT_IN_CART : 'ADD_PRODUCT_IN_CART',
    ADD_PRODUCT_AGAIN_IN_CART : 'ADD_PRODUCT_AGAIN_IN_CART',
    REMOVE_PRODUCT_FROM_CART : ' REMOVE_PRODUCT_FROM_CART',
    REMOVE_SECOND_ENTRY_OF_PRODUCT : 'REMOVE_SECOND_ENTRY_OF_PRODUCT',
    REMOVE_ALL_SECOND_ENTRY_OF_PRODUCT : 'REMOVE_ALL_SECOND_ENTRY_OF_PRODUCT'
}

